image: docker:latest

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build:
  stage: build
  script:
    - docker pull "$CI_REGISTRY_IMAGE":latest || true
    - docker build --cache-from "$CI_REGISTRY_IMAGE":latest --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
